name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with: {submodules: true}
    - run: scripts/test

  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with: {submodules: true}
    - run: scripts/build
    - run: scripts/build-image
    - uses: actions/upload-artifact@v1
      with:
        name: image
        path: image

  push-image:
    needs: [build-image]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v1
      with: {name: image}
    - uses: docker://concourse/registry-image-resource
      with: {entrypoint: scripts/push-image}
      env:
        REPOSITORY: docker.pkg.github.com/${{ github.repository }}/oci-build-task
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
